version = "3.8.3"
runner.dialect = scala213
maxColumn = 100
align.preset = more
align.tokens."+" = [
  { code = "=>",  owner = "Case" },
  { code = "%",   owner = "Term.ApplyInfix" },
  { code = "%%",  owner = "Term.ApplyInfix" },
  { code = ":=",  owner = "Term.ApplyInfix" },
  { code = "+=",  owner = "Term.ApplyInfix" },
  { code = "++=", owner = "Term.ApplyInfix" }
]
newlines.alwaysBeforeElseAfterCurlyIf = true
rewrite.rules = [RedundantBraces, SortImports]
docstrings.style = SpaceAsterisk
