package com.criticalinfra.connectors.jdbc

import com.criticalinfra.config.SourceConfig
import com.criticalinfra.connectors.watermark.WatermarkStore
import com.criticalinfra.engine.ConnectorError

// =============================================================================
// OracleJdbcConnector — Oracle Database JDBC connector
//
// Extends JdbcConnectorBase with Oracle-specific URL construction (service-name
// thin-driver format), optional Oracle Wallet authentication, and ROWID-based
// parallel partitioning for tables without a suitable numeric column.
//
// IMPORTANT: ojdbc11 is NOT on the compile or test classpath. The connector is
// usable without the Oracle driver jar — only testConnection will fail at
// runtime if the jar is absent.  All tests use a TestableOracleConnector that
// overrides testConnection to bypass driver loading.
// =============================================================================

/** Oracle Database JDBC connector using the Thin driver.
  *
  * Generates connection URLs in the service-name format:
  * {{{
  *   jdbc:oracle:thin:@//host:port/service
  * }}}
  * Both `@//host:port/service` (generated by this connector) and the equivalent
  * `@host:port/service` format are accepted by ojdbc11 at runtime, but this implementation always
  * generates the `@//` variant.
  *
  * ==Oracle type-handling notes==
  *
  * '''DATE includes time.''' Oracle's `DATE` type stores both date and time (unlike SQL standard
  * `DATE`). Spark maps Oracle `DATE` to `TimestampType`. Do not assume a `DATE` column is
  * date-only.
  *
  * '''TIMESTAMP WITH TIME ZONE.''' Oracle `TIMESTAMP WITH TIME ZONE` columns are read as strings by
  * the Thin JDBC driver unless `oracle.jdbc.J2EE13Compliant=true` is set as a JDBC connection
  * property. Set this via `extraJdbcOptions` if time-zone preservation is required.
  *
  * '''NUMBER precision.''' Oracle `NUMBER` without explicit precision maps to `DecimalType(38,10)`
  * in Spark by default. For integer-valued NUMBER columns used as watermarks or partition bounds,
  * cast explicitly in the source query to avoid precision-loss surprises.
  *
  * ==Oracle Wallet authentication==
  *
  * When `walletPath` is supplied, the connector injects `oracle.net.wallet_location` into the Spark
  * JDBC options. The wallet path must be resolved from the secrets manager (e.g. HashiCorp Vault or
  * AWS KMS) ''before'' constructing this connector — it must be the on-disk directory path, not a
  * raw `credentialsRef` string. For Wallet-authenticated connections, the JDBC URL typically uses
  * `/@` (no credentials embedded in the URL) and authentication is provided entirely by the wallet.
  *
  * ==ROWID-based parallel partitioning==
  *
  * @param table
  *   Source table or view name (schema-qualified if necessary, e.g. `"FINANCE.TRADES"`).
  * @param watermarkStore
  *   Store used to read and write incremental-extraction high-water marks.
  * @param maxAttempts
  *   Maximum number of connection attempts via [[com.criticalinfra.connectors.RetryPolicy]].
  *   Default: 3.
  * @param retryDelayFn
  *   Function that receives a delay in milliseconds and performs the actual sleep. Inject a no-op
  *   (`_ => ()`) in unit tests to avoid real delays. Default: [[Thread.sleep]].
  * @param walletPath
  *   Absolute path to the Oracle Wallet directory (e.g. `"/opt/oracle/wallet"`). When `Some`, the
  *   `oracle.net.wallet_location` JDBC property is set automatically. When `None` (the default),
  *   standard username/password authentication is assumed. See Oracle Wallet authentication note
  *   above.
  * @param partitionCol
  *   Column name used to split the JDBC read into parallel Spark partitions. When set to `"ROWID"`,
  *   enables Oracle ROWID-based parallel reads for tables that do not expose a suitable sequential
  *   numeric column. `partitionLower` and `partitionUpper` must be set to valid ROWID values (as
  *   `Long` hash representations) retrieved by querying `MIN(ROWID)` and `MAX(ROWID)` from Oracle
  *   before starting the pipeline. When `None` (the default), parallel partitioning is disabled.
  * @param partitionLower
  *   Inclusive lower bound for parallel partitioning. Must be set when `partitionCol` is `Some`.
  * @param partitionUpper
  *   Inclusive upper bound for parallel partitioning. Must be set when `partitionCol` is `Some`.
  */
class OracleJdbcConnector(
    private val table: String,
    watermarkStore: WatermarkStore,
    maxAttempts: Int = 3,
    retryDelayFn: Long => Unit = Thread.sleep,
    private val walletPath: Option[String] = None,
    private val partitionCol: Option[String] = None,
    private val partitionLower: Option[Long] = None,
    private val partitionUpper: Option[Long] = None
) extends JdbcConnectorBase(watermarkStore, maxAttempts, retryDelayFn) {

  // ---------------------------------------------------------------------------
  // Abstract method implementations
  // ---------------------------------------------------------------------------

  /** Fully-qualified JDBC driver class name for the Oracle Thin driver.
    *
    * The string constant `"oracle.jdbc.OracleDriver"` is returned without loading the class — the
    * driver jar (ojdbc11) is not required on the classpath to compile or unit-test this connector.
    */
  override protected def driverClass: String = "oracle.jdbc.OracleDriver"

  /** Source table or view name, returned directly from the constructor parameter.
    *
    * @param config
    *   Pipeline configuration (not used; the table name is set at construction time).
    * @return
    *   The table name passed to the constructor.
    */
  override protected def tableName(config: SourceConfig): String = table

  /** Builds the Oracle Thin JDBC connection URL in service-name format.
    *
    * Requires `host`, `port`, and `database` (used as the Oracle service name) to be present in
    * `config.connection`. Returns `Left(ConnectorError)` if any of the three fields is absent.
    *
    * The legacy `jdbc:oracle:thin:@host:port:SID` (SID-colon) format is intentionally not
    * supported. Only the `@//host:port/service` (service-name) format is generated.
    *
    * @param config
    *   Pipeline configuration from which host, port, and service name (database) are read.
    * @return
    *   `Right("jdbc:oracle:thin:@//host:port/service")` on success; `Left(ConnectorError)` if host,
    *   port, or database is absent.
    */
  override protected def jdbcUrl(config: SourceConfig): Either[ConnectorError, String] =
    (config.connection.host, config.connection.port, config.connection.database) match {
      case (Some(host), Some(port), Some(service)) =>
        Right(s"jdbc:oracle:thin:@//$host:$port/$service")
      case _ =>
        Left(
          ConnectorError(
            config.metadata.sourceId,
            "Oracle connector requires host, port, and database (service name) in the connection configuration"
          )
        )
    }

  // ---------------------------------------------------------------------------
  // Parallel-read partitioning overrides
  // ---------------------------------------------------------------------------

  /** Column name used to split the JDBC read into parallel Spark partitions.
    *
    * When set to `"ROWID"`, enables Oracle ROWID-based parallel reads for tables that do not expose
    * a suitable sequential numeric column. `partitionLower` and `partitionUpper` must be set to
    * valid ROWID values (as `Long` hash representations) retrieved by querying `MIN(ROWID)` and
    * `MAX(ROWID)` from Oracle before starting the pipeline. When `None` (the default), parallel
    * partitioning is disabled.
    *
    * @param config
    *   Pipeline configuration (not used; the value is set at construction time).
    */
  override protected def partitionColumn(config: SourceConfig): Option[String] = partitionCol

  /** Inclusive lower bound on [[partitionColumn]] for parallel partitioning.
    *
    * @param config
    *   Pipeline configuration (not used; the value is set at construction time).
    */
  override protected def partitionLowerBound(config: SourceConfig): Option[Long] = partitionLower

  /** Inclusive upper bound on [[partitionColumn]] for parallel partitioning.
    *
    * @param config
    *   Pipeline configuration (not used; the value is set at construction time).
    */
  override protected def partitionUpperBound(config: SourceConfig): Option[Long] = partitionUpper

  // ---------------------------------------------------------------------------
  // Oracle Wallet authentication — driver-specific JDBC options
  // ---------------------------------------------------------------------------

  /** Injects Oracle Wallet authentication properties when `walletPath` is set.
    *
    * When `walletPath` is `Some(path)`, adds the `oracle.net.wallet_location` JDBC property in the
    * Oracle `(SOURCE=...)` descriptor format required by ojdbc11.
    *
    * The wallet path must be resolved from the secrets manager before constructing this connector —
    * it must be the on-disk directory path, not a raw `credentialsRef` string. For Wallet-
    * authenticated connections, the JDBC URL typically uses `/@` (no credentials embedded in the
    * URL) and authentication is provided entirely by the wallet.
    *
    * When `walletPath` is `None`, returns an empty map so standard username/password authentication
    * is used.
    *
    * @param config
    *   Pipeline configuration (not used; the wallet path is set at construction time).
    * @return
    *   Map containing `oracle.net.wallet_location` when wallet auth is configured; empty map
    *   otherwise.
    */
  override protected def extraJdbcOptions(config: SourceConfig): Map[String, String] =
    walletPath match {
      case Some(path) =>
        Map(
          "oracle.net.wallet_location" ->
            s"(SOURCE=(METHOD=FILE)(METHOD_DATA=(DIRECTORY=$path)))"
        )
      case None => Map.empty
    }
}
